### ISSUE TITLE
is there a mortality API for New York state? 

### ISSUE THREAD

**Issue by bennek2** [TheRensselaerIDEA/COVID-Notebooks#11]
If so then make it work.

**Comment by olyerickson** [comment]
@thomashopkins32 said he would look into this. Update? 

We need a live feed for this table so @olyerickson doesn't have to hand-scrape it every day!!
https://covid19tracker.health.ny.gov/views/NYS-COVID19-Tracker/NYSDOHCOVID-19Tracker-Fatalities?%3Aembed=yes&%3Atoolbar=no&%3Atabs=n#/views/NYS%2dCOVID19%2dTracker/NYSDOHCOVID%2d19Tracker%2dFatalities

**Comment by thopkins32** [comment]
I looked around and couldn’t find any APIs specific to covid-19 for NYS County level mortality. I expected it to be available alongside the testing dataset here: https://health.data.ny.gov/browse?tags=covid-19 but for some reason it isn’t.

**Comment by thopkins32** [comment]
I found a data source here that gets updated daily: https://github.com/nytimes/covid-19-data 
This has the mortality rates for covid-19 for all the counties in the US

I can work on integrating this.

**Comment by bennek2** [comment]
Awesome Thomas

Sent from my iPhone

On Apr 10, 2020, at 2:18 PM, Thomas Hopkins <notifications@github.com> wrote:

﻿

I found a data source here that gets updated daily: https://github.com/nytimes/covid-19-data
This has the mortality rates for covid-19 for all the counties in the US

I can work on integrating this.
